name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: devcontainer
      uses: ./.github/workflows/actions/devcontainer
      id: devcontainer
    - name: setup
      run: |
        echo 'EXEC=${{ steps.devcontainer.outputs.exec }}' >> $GITHUB_ENV
    - name: build
      run: |
        ${{ env.EXEC }} make
    - name: Cache Models
      uses: actions/cache@v4
      with:
        path: test/models
        key: models-${{ hashFiles('Makefile', 'vendored/ggml/examples/gpt-2/download-ggml-model.sh') }}
    - name: models
      run: |
        ${{ env.EXEC }} make models
    - name: runtest
      run: |
        ${{ env.EXEC }} make runtest
