name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: devcontainer
      uses: ./.github/workflows/actions/devcontainer
      id: devcontainer
    - name: setup
      run: |
        echo 'EXEC=${{ steps.devcontainer.outputs.exec }}' >> $GITHUB_ENV
    - name: patch
      run: |
        ${{ env.EXEC }} make patch
    - name: build
      run: |
        ${{ env.EXEC }} make
    - name: Cache Models
      uses: actions/cache@v4
      with:
        path: models
        key: models-${{ hashFiles('Makefile') }}
    - name: models
      run: |
        ${{ env.EXEC }} make models
    - name: runtest
      run: |
        ${{ env.EXEC }} make runtest
    - name: simple
      run: |
        ${{ env.EXEC }} make simple
    - name: llama-simple
      run: |
        ${{ env.EXEC }} make llama-simple
    - uses: actions/upload-artifact@v4
      with:
        name: model-graphs
        path: _build/json
        retention-days: 7
